#!/usr/bin/env node
// Writes ENDPOINTS.md from the route table. `npm run docs` after adding a route;
// a test fails when the file is out of date.

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { ROUTES } from '../src/server.js';

const AREAS = ['Organizations', 'Networks', 'Devices', 'Alerts', 'Security appliance (MX)', 'Switches (MS)', 'Wireless (MR)'];

function areaOf(p) {
  if (p.includes('/assurance/') || p.includes('/health/alerts')) return 'Alerts';
  if (p.includes('/appliance/')) return 'Security appliance (MX)';
  if (p.includes('/switch/') || p.endsWith('/lldpCdp')) return 'Switches (MS)';
  if (p.includes('/wireless/')) return 'Wireless (MR)';
  if (p.startsWith('/organizations')) return 'Organizations';
  return p.startsWith('/networks') ? 'Networks' : 'Devices';
}

export function endpointsMarkdown() {
  const groups = new Map(AREAS.map((name) => [name, []]));
  for (const r of ROUTES) groups.get(areaOf(r.path)).push(r);
  const writes = ROUTES.filter((r) => r.method !== 'GET').length;
  let md = '# Endpoints\n\n';
  md += `The emulator answers these ${ROUTES.length} operations under \`/api/v1\`: ${ROUTES.length - writes} reads and ${writes} writes. Names match the operation IDs in the official OpenAPI spec and the Meraki SDKs. Anything else returns \`404\`, or \`405\` for a method a path doesn't support.\n\n`;
  md += 'This file is generated by `npm run docs`.\n';
  // The operation goes under its path: side by side, the longest rows are wider than GitHub's page.
  for (const [name, routes] of groups) {
    md += `\n## ${name}\n\n| Method | Path and operation |\n| --- | --- |\n`;
    const order = ['GET', 'POST', 'PUT', 'DELETE'];
    const sorted = [...routes].sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : order.indexOf(a.method) - order.indexOf(b.method)));
    for (const r of sorted) md += `| ${r.method} | \`${r.path}\`<br>${r.op} |\n`;
  }
  return md;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(new URL('../ENDPOINTS.md', import.meta.url), endpointsMarkdown());
}
